### ISSUE TITLE
NullReferenceException in new Hook with tModLoader x64

### ISSUE THREAD

**Issue by Avadonia** [0x0ade/TerrariaHooks#3]
Hello, would you consider making TerrariaHooks to make it work with the 64bit version of Tmodloader ? i get this error when i try to load it :
http://prntscr.com/mx4s2w
Thanks

**Comment by 0x0ade** [comment]
The 64-bit version of tModLoader is not officially supported, neither by the tML dev team, nor by me.

TerrariaHooks itself supports 64-bit environments just fine. tML loads the bundled `Mono.dll` on Linux and macOS, which both support 64-bit. I've made sure to fix as many Linux and macOS 64-bit issues as possible together with Chicken Bones from the official tML team. Unfortunately I can't fix all bugs introduced in combination with unofficial tML forks.

I've forwarded this issue to Dradonhunter11, who - as far as I know - is responsible for tML x64.

I'm also going to change this issue's misleading name.

**Comment by 0x0ade** [comment]
Please put the .tmod file from the latest TerrariaHooks.zip in this message into your Mods folder and try again.

~~https://github.com/0x0ade/TerrariaHooks/commit/dc794866c35e809e8410e082ccd99c81790942a8: [TerrariaHooks.zip](https://github.com/0x0ade/TerrariaHooks/files/2963873/TerrariaHooks.zip)~~

https://github.com/0x0ade/TerrariaHooks/commit/2e75c7395805b4197386dbc293947358f05cf359: [TerrariaHooks.zip](https://github.com/0x0ade/TerrariaHooks/files/2963939/TerrariaHooks.zip)

**Comment by 0x0ade** [comment]
Turns out there might be an unfixable issue due to how Dradonhunter is mixing both tML 0.10 and tML 0.11 code in his fork. The commits above try to take that into account when resolving specific base hooking points.

Unfortunately, that means:
- There's still a chance that TerrariaHooks won't work with "tML x64" until it fully upgrades to 0.11.
- Even if TerrariaHooks itself would work fine, not all mods will run properly with "tML x64".

I'll mark this issue as wontfix on my end and I'll try to point Dradonhunter towards fixing this on "tML x64"'s end. Right now the options are downgrading Mono.Cecil in "tML x64" or fully upgrading its tML code to 0.11.

**Comment by BasedOnPixels** [comment]
Some mods are working fine with the 0.20 build of TerrariaHooks on 64bit. But some seem to be breaking. Is that related to the above issue or could that be fixed?

[12:12:13] [7/INFO] [tML]: Adding Recipes...
[12:12:13] [7/ERROR] [tML]: An error occurred while loading ModLoader
The mod(s) have been automatically been disabled.
System.NullReferenceException: Object reference not set to to an instance of an object.
   at DALib.UI.SetLoadingMessage(String message, Single progress, String submessage) in c:\Users\Ashley\Documents\My Games\Terraria\ModLoader\Mod Sources\DALib\DALib.cs:Zeile 87.
   at Terraria.ModLoader.RecipeHooks.AddRecipes()
   at Terraria.Recipe.SetupRecipes()
   at Terraria.ModLoader.ModContent.SetupRecipes()
   at Terraria.ModLoader.ModContent.Load()
   at Terraria.ModLoader.ModLoader.Load()
[12:12:13] [7/INFO] [tML]: Disabling Mod: ModLoader

**Comment by 0x0ade** [comment]
That's a separate issue with DALib. Please contact Dark-Assassin about it, f.e. on the tML Discord server.
